const ACTIVITY_TYPES = Object.freeze({
  AUTH_REGISTER: 'AUTH_REGISTER',
  AUTH_LOGIN: 'AUTH_LOGIN',
  AUTH_LOGOUT: 'AUTH_LOGOUT',
  AUTH_REFRESH_TOKEN: 'AUTH_REFRESH_TOKEN',
  AUTH_OAUTH_LOGIN: 'AUTH_OAUTH_LOGIN',
  POST_CREATE: 'POST_CREATE',
  POST_UPDATE: 'POST_UPDATE',
  POST_DELETE: 'POST_DELETE',
  POST_RESTORE: 'POST_RESTORE',
  COMMENT_CREATE: 'COMMENT_CREATE',
  COMMENT_UPDATE: 'COMMENT_UPDATE',
  COMMENT_DELETE: 'COMMENT_DELETE',
  ADMIN_UPDATE_USER_ROLE: 'ADMIN_UPDATE_USER_ROLE',
  ADMIN_UPDATE_USER_STATUS: 'ADMIN_UPDATE_USER_STATUS',
  ADMIN_DELETE_USER: 'ADMIN_DELETE_USER',
});

module.exports = {
  ACTIVITY_TYPES,
};
